[2025-04-02T16:39:57.939-0400] {processor.py:161} INFO - Started process (PID=69691) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:39:57.940-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:39:57.940-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:39:57.940-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:39:57.956-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:39:57.954-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:39:57.956-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:39:57.956-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:39:57.956-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:39:58.011-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-04-02T16:41:25.135-0400] {processor.py:161} INFO - Started process (PID=80637) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:41:25.137-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:41:25.137-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:41:25.137-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:41:25.154-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:41:25.152-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:41:25.154-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:41:25.154-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:41:25.154-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:41:25.205-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2025-04-02T16:43:19.921-0400] {processor.py:161} INFO - Started process (PID=94843) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:43:19.923-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:43:19.923-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:43:19.923-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:43:19.938-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:43:19.937-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:43:19.939-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:43:19.939-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:43:19.939-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:43:19.994-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2025-04-02T16:46:20.319-0400] {processor.py:161} INFO - Started process (PID=17529) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:46:20.320-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:46:20.320-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:46:20.320-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:46:20.336-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:46:20.334-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:46:20.336-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:46:20.336-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:46:20.336-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:46:20.386-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-04-02T16:47:48.348-0400] {processor.py:161} INFO - Started process (PID=28488) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:47:48.350-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:47:48.350-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:47:48.350-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:47:48.366-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:47:48.364-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:47:48.366-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:47:48.366-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:47:48.366-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:47:48.415-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-04-02T16:51:31.155-0400] {processor.py:161} INFO - Started process (PID=56064) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:51:31.156-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:51:31.156-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:51:31.156-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:51:31.172-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:51:31.170-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:51:31.172-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:51:31.172-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:51:31.172-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:51:31.226-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-04-02T16:52:57.990-0400] {processor.py:161} INFO - Started process (PID=66797) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:52:57.992-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:52:57.992-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:52:57.992-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:52:58.009-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:52:58.007-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:52:58.009-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:52:58.009-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:52:58.009-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:52:58.072-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2025-04-02T16:54:48.362-0400] {processor.py:161} INFO - Started process (PID=80419) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:54:48.364-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:54:48.364-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:54:48.364-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:54:48.381-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:54:48.379-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:54:48.381-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:54:48.381-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:54:48.381-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:54:48.429-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2025-04-02T16:56:44.058-0400] {processor.py:161} INFO - Started process (PID=94799) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:56:44.059-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:56:44.059-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:56:44.059-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:56:44.075-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:56:44.073-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:56:44.075-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:56:44.075-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:56:44.075-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:56:44.121-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2025-04-02T16:58:36.619-0400] {processor.py:161} INFO - Started process (PID=8928) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:58:36.621-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T16:58:36.621-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:58:36.621-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:58:36.637-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:58:36.635-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T16:58:36.637-0400] {logging_mixin.py:188} INFO - [2025-04-02T16:58:36.637-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T16:58:36.637-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T16:58:36.684-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2025-04-02T17:00:29.216-0400] {processor.py:161} INFO - Started process (PID=22763) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:00:29.218-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T17:00:29.219-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:00:29.219-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:00:29.235-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:00:29.233-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T17:00:29.235-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:00:29.235-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T17:00:29.235-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:00:29.282-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-04-02T17:02:22.113-0400] {processor.py:161} INFO - Started process (PID=36606) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:02:22.114-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T17:02:22.114-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:02:22.114-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:02:22.131-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:02:22.129-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T17:02:22.131-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:02:22.131-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T17:02:22.131-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:02:22.179-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2025-04-02T17:04:14.104-0400] {processor.py:161} INFO - Started process (PID=50368) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:04:14.106-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T17:04:14.107-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:04:14.106-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:04:14.124-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:04:14.122-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T17:04:14.124-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:04:14.124-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T17:04:14.124-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:04:14.180-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2025-04-02T17:06:02.014-0400] {processor.py:161} INFO - Started process (PID=63542) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:06:02.016-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T17:06:02.016-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:06:02.016-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:06:02.030-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:06:02.029-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T17:06:02.031-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:06:02.030-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T17:06:02.031-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:06:02.077-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2025-04-02T17:07:54.860-0400] {processor.py:161} INFO - Started process (PID=77579) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:07:54.862-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T17:07:54.862-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:07:54.862-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:07:54.879-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:07:54.877-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T17:07:54.879-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:07:54.879-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T17:07:54.880-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:07:54.928-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2025-04-02T17:09:51.232-0400] {processor.py:161} INFO - Started process (PID=91944) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:09:51.234-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T17:09:51.234-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:09:51.234-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:09:51.250-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:09:51.248-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T17:09:51.250-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:09:51.250-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T17:09:51.250-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:09:51.303-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-04-02T17:11:41.475-0400] {processor.py:161} INFO - Started process (PID=5829) to work on /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:11:41.476-0400] {processor.py:830} INFO - Processing file /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-04-02T17:11:41.476-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:11:41.476-0400] {dagbag.py:540} INFO - Filling up the DagBag from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:11:41.493-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:11:41.490-0400] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-04-02T17:11:41.493-0400] {logging_mixin.py:188} INFO - [2025-04-02T17:11:41.493-0400] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-04-02T17:11:41.493-0400] {processor.py:842} WARNING - No viable dags retrieved from /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-04-02T17:11:41.544-0400] {processor.py:183} INFO - Processing /Users/prasenjeet.gadhe/Documents/05. Nokia_PoV/Parallel_Test/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.070 seconds
